config/routes.rb
Rails.application.routes.draw do
  get 'travel_plans/new'

  devise_for :users
  resources :new_request
  resources :comments
  resources :requests do
    member do
      post 'deposit'
      post 'item_bought'
      post 'item_delivered'
      post 'cancel_request'
      post 'cancel_offer'
      post 'reject'
      post 'cancel_request_manage'
      post 'cancel_offer_manage'
      post 'rate'
    end
    resources :offers
  end
  resources :travel_plans
  get '/manage/request' => 'manager#requests'
  get '/manage/trip' => 'manager#trips'
  get '/inbox' => 'inbox#show'
  root 'home#index'
  get '/trip' => 'trips#new'
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :authenticate_user! 
  def requests
    @requests = current_user.requests
    @offers = current_user.offers
  end

  def trips
    @travel_plans = current_user.travel_plans
  end
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/_offer_table.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel">
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Request name</th>
              <th>Picture</th>
              <th>Request selling location</th>
              <th>Your offer price</th>
              <th>Your return date</th>
              <th>Request status</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <% @offers.each do |offer| %>
              <tr>
                <td><%= link_to offer.request.name, request_path(offer.request) %></td>
                <td class="centered"><%= image_tag offer.request.picture_url, height: 64, width: 64 %></td>
                <td><%= Location.find_by_id(offer.request.selling_location_id).name %></td>
                <td><%= offer.price %> VND</td>
                <td><%= offer.arrival_date.strftime("%d/%m/%Y") %></td>
                <td class="centered" style="vertial-align: middle">
                    <h4>
                      <span class="label <%= status_color_for(offer.request.status_to_s) %>">
                        <%= offer.request.status_to_s %></span>
                    </h4>
                </td>
                <td align="center" class="text-left">
                  <%= link_to request_path(offer.request), class:"btn btn-default", 
                    data: {toggle: "tooltip", placement: "top"},
                     title: "Go to request" do %>
                     <span class="glyphicon glyphicon-search"></span>
                   <% end %>
                   <%= form_tag cancel_offer_manage_request_path(offer.request), 
                     method: "post", class: "inline", remote: true do %>
                    <%= button_tag(type: "submit", class: "btn btn-default", 
                      data: {toggle: "tooltip", placement: "top", confirm: "Are you sure?"},
                      title: "Cancel") do %>
                     <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                   <% end %>
                 </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/manager/_request_table.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel">
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Picture</th>
              <th>Selling location</th>
              <th>Status</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <% @requests.each do |request| %>
              <tr>
                <td><%= link_to request.name, request_path(request) %></td>
                <td><%=  request.description %></td>
                <td class="centered"><%= image_tag request.picture_url, height: 64, width: 64 %></td>
                <td><%= Location.find_by_id(request.selling_location_id).name %></td>
                <td class="centered" style="vertial-align: middle">
                    <h4>
                      <span class="label <%= status_color_for(request.status_to_s) %>">
                        <%= request.status_to_s %></span>
                    </h4>
                </td>
                <td align="center" class="text-left">
                  <%= link_to request_path(request), class:"btn btn-default", 
                    data: {toggle: "tooltip", placement: "top"},
                     title: "Go to request" do %>
                     <span class="glyphicon glyphicon-search"></span>
                   <% end %>
                  <%= link_to edit_request_path(request), class:"btn btn-default", 
                    data: {toggle: "tooltip", placement: "top"},
                     title: "Edit" do %>
                     <span class="glyphicon glyphicon-pencil"></span>
                   <% end %>
                   <%= form_tag cancel_request_manage_request_path(request), 
                     method: "post", class: "inline", remote: true do %>
                    <%= button_tag(type: "submit", class: "btn btn-default", 
                      data: {toggle: "tooltip", placement: "top", confirm: "Are you sure?"},
                      title: "Cancel") do %>
                     <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                   <% end %>

                 </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/manager/_trip_table.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel">
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Location</th>
              <th>Return date</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <% @travel_plans.each do |trip| %>
              <tr>
                <td><%= link_to Location.find_by_id(trip.location_id).name,
                requests_path(location: Location.find_by_id(trip.location.id).name)%></td>
                <td><%= trip.return_date.strftime("%d/%m/%Y") %></td>
                <td align="center" class="text-left">
                  <%= link_to requests_path(location: Location.find_by_id(trip.location.id).name), 
                    class:"btn btn-default", 
                    data: {toggle: "tooltip", placement: "top"},
                     title: "Go to Location" do %>
                     <span class="glyphicon glyphicon-search"></span>
                   <% end %>
                  <%= link_to edit_travel_plan_path(trip), class:"btn btn-default", 
                    data: {toggle: "tooltip", placement: "top"},
                     title: "Edit" do %>
                     <span class="glyphicon glyphicon-pencil"></span>
                   <% end %>
                   <%= link_to travel_plan_path(trip), method: :delete, 
                     class:"btn btn-default", 
                     data: {toggle: "tooltip", placement: "top", 
                            confirm: "are you sure?" },
                     title: "Delete" do %>
                     <span class="glyphicon glyphicon-remove"></span>
                   <% end %>
                 </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/manager/requests.html.erb
<%= flash_messages %>
<div class="row">
  <div class= "col-sm-6">
    <%= link_to "New Request", '/new_request/', class: "btn btn-success" %>
  </div>
  <div class="col-sm-6">
    <%= link_to "Browse for new offer", requests_path, class: "btn pull-right btn-primary" %>
  </div>
</div>
<hr>
<h2 class="text-center">
  Your Request
</h2>
<%= render 'request_table' %>
<h2 class="text-center">
  Your Offer
</h2>
<%= render 'offer_table' %>

app/views/manager/trips.html.erb
<div class="row">
  <div class= "col-sm-6">
    <%= link_to "New Trip", new_travel_plan_path, class: "btn btn-success" %>
  </div>
</div>
<hr>
<h2 class="text-center">
  Your trips
</h2>
<%= render "trip_table" %>