config/routes.rb
Rails.application.routes.draw do
  get 'travel_plans/new'

  devise_for :users
  resources :new_request
  resources :comments
  resources :requests do
    member do
      post 'deposit'
      post 'item_bought'
      post 'item_delivered'
      post 'cancel_request'
      post 'cancel_offer'
      post 'reject'
      post 'cancel_request_manage'
      post 'cancel_offer_manage'
      post 'rate'
    end
    resources :offers
  end
  resources :travel_plans
  get '/manage/request' => 'manager#requests'
  get '/manage/trip' => 'manager#trips'
  get '/inbox' => 'inbox#show'
  root 'home#index'
  get '/trip' => 'trips#new'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
  validates :content, presence: true, length: { minimum: 5, maximum: 255 } 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    @request = Request.find params[:comment][:request_id]
    if @comment.save
      respond_to do |format|
        format.js {
          flash[:success] = "Your comment is created"
        }
        format.html {
          flash[:success] = "Your comment is created"
          redirect_to request_path(@request)
        }
      end
    else
      respond_to do |format|
        format.js {
          flash[:error] = "Your comment is too short (minimum is 5 characters)"
        }
        format.html {
          flash[:error] = "Your comment is too short (minimum is 5 characters)"
          redirect_to request_path(@request)
        }
      end
    end
  end
  private
    def comment_params
      params.require(:comment).permit(:content, :request_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-xs-2">
      <img class="img-circle avatar pull-right" 
      src=<%= User.find_by_id(comment.user_id).avatar%>>
  </div>

  <div class="col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= User.find_by_id(comment.user_id).email %></strong> 
        <span class="text-muted"><small><%= time_ago_in_words(comment.created_at) %> ago</small> </span>
      </div>
      <div class="panel-body">
        <%= comment.content %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<% unless current_user.nil? %>
    <div class="row">
      <div class="col-xs-2" style="padding: 0px">
          <img class="img-circle avatar pull-right" 
          src=<%= current_user.avatar%>>
      </div>
      <div class="col-xs-10 ">
        <%= form_for Comment.new, remote: true, method: :post, url: comments_path,
          html: {class: "form center"} do |f| %>
          <%= f.hidden_field :request_id, :value => @request.id %>
          <%= f.text_area :content, class:"form-control" %>
          <br \>
          <%= f.submit "Submit", class:"btn btn-primary " %>
        <% end %>
      </div>
    </div>
  <br />
<% else %>
  <div class="row">
    <div class="col-xs-10 col-md-offset-2">
      <div class="text-center">
        <hr />
        <a href="<%= new_user_session_path %>" class="btn btn-success">Sign in to comment</a>
      </div>
    </div>
  </div>
  <br />
<% end %>

app/views/comments/create.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @comment.errors.empty? %>
  $('#comment_content').val('');
  var content = "<%= j render @comment %>";
  window.ws.send(JSON.stringify({ content: content, event: 'comment_create', request_id: '<%= @request.id %>' }));
<% end %>