config/routes.rb
Rails.application.routes.draw do
  get 'travel_plans/new'

  devise_for :users
  resources :new_request
  resources :comments
  resources :requests do
    member do
      post 'deposit'
      post 'item_bought'
      post 'item_delivered'
      post 'cancel_request'
      post 'cancel_offer'
      post 'reject'
      post 'cancel_request_manage'
      post 'cancel_offer_manage'
      post 'rate'
    end
    resources :offers
  end
  resources :travel_plans
  get '/manage/request' => 'manager#requests'
  get '/manage/trip' => 'manager#trips'
  get '/inbox' => 'inbox#show'
  root 'home#index'
  get '/trip' => 'trips#new'
end

app/models/request.rb
class Request < ActiveRecord::Base
  before_save :set_picture_url_default
  belongs_to :delivery_method
  belongs_to :selling_location, class_name: 'Location'
  belongs_to :delivery_location, class_name: 'Location'
  has_many :comments, dependent: :destroy
  has_one :selected_offer, class_name: 'Offer'

  belongs_to :requester, class_name: 'User'

  validates :description, presence: true, if: :active_or_item?
  validates :requester, presence: true, if: :check_validate?
  validates :delivery_method_id, presence: true, if: :check_validate?
  validates :selling_location_id, presence: true, if: :check_validate?
  #validates :delivery_location, presence: true, if: :check_validate?
  validates :offer_price, presence: true, numericality: {greater_than_or_equal_to: 0}, if: :check_validate?
  validates :name, presence: true, if: :active_or_item?
  validates :quantity, presence: true
  validates :status, presence: true
  
  default_scope { order(created_at: :desc ) }
  scope :ordered_by_status, -> { order('status ASC') }

  enum status: [:open, :pending_deposit, :deposited, :waiting_delivery, :completed]

  def can_make_new_offer?(user)
    open? && user.id != requester_id
  end

  def has_offered?
    pending_deposit?
  end

  def can_make_deposit?(user)
    has_offered? && user.id == requester_id
  end

  def make_deposit(stripe_token)
    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://dashboard.stripe.com/account/apikeys
    Stripe.api_key = 'sk_test_Dpwz47km7ZMFxoJi1rb2ucrJ'

    charge = Stripe::Charge.create(
        :amount => (selected_offer.price + (selected_offer.price * 0.07 + 50000)).to_i,
        :currency => 'vnd',
        :source => stripe_token,
        :description => "Deposit for request #{id}"
    )
    self.status = :deposited
    self.has_deposited = true
    self.save

    charge
  end

  def item_bought
    self.status = :waiting_delivery
    self.save
  end

  def item_delivered
    self.status = :completed
    self.save
  end

  def can_make_purchase?(user)
    deposited? && user.id == self.selected_offer.carrier_id
  end

  def can_make_deliver?(user)
    waiting_delivery? && user.id == self.requester_id
  end

  def new_offer(user, price = self.offer_price, arrival_date = Date.now)
    if self.open?
      offer_opts = {
          carrier: user,
          request: self,
          price: price,
          arrival_date: arrival_date
      }
      offer = Offer.create(offer_opts)
      if offer.errors.empty?
        if self.has_deposited?
          self.status = :deposited
        else
          self.status = :pending_deposit
        end
        self.save
      else
        offer.errors.each do |key|
          self.errors.add(key, offer.errors[key])
        end
      end
    else
      self.errors.add(:base, 'Can only make new offer on open request')
    end
    self
  end

  def cancel
    if self.selected_offer
      self.selected_offer.delete
    end
    if self.comments
      self.comments.delete_all
    end
    self.delete
  end

  def cancel_offer
    self.selected_offer.delete
    self.status = :open
    self.save
  end

  def reject
    self.selected_offer.delete
    self.status = :open
    self.save
  end

  def can_give_review?(user)
    self.completed? && (can_give_requester_review?(user) || can_give_helper_review?(user))
  end

  def can_give_requester_review?(user)
    self.requester_id == user.id && Review.where(reviewer_id: user.id, request_id: self.id).empty?
  end

  def can_give_helper_review?(user)
    self.selected_offer.carrier_id == user.id && Review.where(reviewer_id: user.id, request_id: self.id).empty?
  end

  def review(user, rating)
    if can_give_review?(user)
      data = {
          reviewer_id: user.id,
          score: rating,
          offer_id: selected_offer.id,
          request_id: id
      }
      if can_give_requester_review?(user)
        data = data.merge(reviewee_id: selected_offer.carrier_id)
      elsif can_give_helper_review?(user)
        data = data.merge(reviewee_id: requester_id)
      end
      new_review = Review.create(data)
      update_score(new_review.reviewee_id)
    end
  end

  def check_validate?
    check_validate == 'active'
  end

  def active_or_item?
    check_validate.include?('item') || check_validate?
  end

  def active_or_location?
    check_validate.include?('location') || check_validate?
  end

  def active_or_price?
    check_validate.include?('price') || check_validate?
  end

  def self.search(search)
    where { (name =~ "%#{search}%") | (description =~ "%#{search}%") }
  end

  def status_to_s
    self.status.capitalize.split('_').join(' ')
  end

  def set_picture_url_default
    if picture_url.blank?
      self.picture_url = "http://i.imgur.com/6uH6x3B.jpg"
    end 
  end

  private
  def update_score(reviewee_id)
    score = Review.where(reviewee_id: reviewee_id).average(:score)
    reviewee = User.find_by_id(reviewee_id)
    reviewee.current_score = score
    reviewee.save
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :load_request, only: [:show, :deposit, :item_bought,
                                      :item_delivered, :cancel_request,
                                      :cancel_offer, :rate, :reject,
                                      :cancel_request_manage, :cancel_offer, 
                                      :cancel_offer_manage, :rate]
  before_action :load_comment, only: [:show]
  before_action :load_request_by_id, only: [:edit, :update, :destroy]
  before_action :check_user_edit, only: [:edit, :update]
  before_action :cheat_web_socket_by_huy
  
  def index
    @requests = Request.all
    unless params[:location].blank? || params[:location] == "All"
      @requests = Location.find_by_name(params[:location]).requests
    end

    if params[:order] == "Status"
      @requests = @requests.ordered_by_status
      if params[:search]
        @requests = @requests.search(params[:search])
      end
    end

    if params[:search]
      @requests = @requests.search(params[:search])
    end

  end

  def show
  end

  def edit
  end

  def update
    @request.check_validate = "active"
    if @request.update(request_params)
      flash[:success] = "Successful update the request"
      redirect_to manage_request_path
    else
      render 'edit'
    end
  end

  def deposit    
    begin
      @request.make_deposit(params[:stripe_token])
      send_deposit_notification

      respond_to do |format|
        format.js
        format.html {
          redirect_to action: :show, id: params[:id]
        }
      end
    rescue Stripe::CardError => e
      flash[:error] = e.message

      respond_to do |format|
        format.js
        format.html {
          redirect_to action: :show, id: params[:id]
        }
      end
    end
  end

  def item_bought
    @request.item_bought
    send_buy_item_notification
    respond_to do |format|
      format.js
      format.html {
        redirect_to action: :show, id: params[:id]
      }
    end
  end

  def item_delivered
    @request.item_delivered
    send_deliver_item_notification
    respond_to do |format|
      format.js
      format.html {
        redirect_to action: :show, id: params[:id]
      }
    end
  end

  def cancel_request
    @receiver_id = @request.selected_offer.carrier_id

    @request.cancel
    send_cancel_request_notification

    respond_to do |format|
      format.js
      format.html {
        redirect_to action: :index
      }
    end
  end

  def cancel_request_manage
    @receiver_id = @request.selected_offer.carrier_id

    @request.cancel
    send_cancel_request_notification

    respond_to do |format|
      format.js {
        flash[:success] = "Successful cancel request"
      }
      format.html {
        flash[:success] = "Successful cancel request"
        redirect_to manage_request_path
      }
    end
  end

  def reject
    @request.reject
    send_reject_notification

    respond_to do |format|
      format.js
      format.html {
        redirect_to action: :show, id: params[:id]
      }
    end
  end

  def cancel_offer
    @request.cancel_offer
    send_cancel_offer_notification

    respond_to do |format|
      format.js
      format.html {
        redirect_to action: :show, id: params[:id]
      }
    end
  end

  def cancel_offer_manage
    @request.cancel_offer
    send_cancel_offer_notification

    respond_to do |format|
      format.js
      format.html {
        redirect_to manage_request_path
      }
    end
  end

  def rate
    @request.review(current_user, params[:rating])
    redirect_to action: :show, id: params[:id]
  end


  private

  def cheat_web_socket_by_huy
    if !!@request
      if !!@request.selected_offer
        @huy_socket = "window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '#{ @request.selected_offer.carrier_id }' }))";
      end
    end
  end

  def load_comment
    @comments = @request.comments
  end

  def send_deposit_notification
    # notify inbox
    DepositNotification.create(
        receiver_id: @request.selected_offer.carrier_id,
        content: "#{@request.requester.email} has deposited money for the request <a href='#{request_url(@request)}'>#{@request.id}</a>",
        event_type: Request.statuses[:deposited])
    DepositNotification.create(
        receiver_id: @request.requester_id,
        content: "You deposited money for the request <a href='#{request_url(@request)}'>#{@request.id}</a>",
        event_type: Request.statuses[:deposited])
  end

  def send_buy_item_notification
    BuyItemNotification.create(
        receiver_id: @request.selected_offer.carrier_id,
        content: "You bought the requested item <a href='#{request_url(@request)}'>##{@request.id}</a>",
        event_type: Request.statuses[:waiting_delivery])
    
    # notify inbox
    BuyItemNotification.create(
        receiver_id: @request.requester_id,
        content: "#{@request.selected_offer.carrier.email} bought the requested item <a href='#{request_url(@request)}'>##{@request.id}</a>",
        event_type: Request.statuses[:waiting_delivery])
  end

  def send_deliver_item_notification
    # notify inbox
    DeliverItemNotification.create(
        receiver_id: @request.selected_offer.carrier_id,
        content: "You delivered the requested item <a href='#{request_url(@request)}'>##{@request.id}</a>",
        event_type: Request.statuses[:completed])
    DeliverItemNotification.create(
        receiver_id: @request.requester_id,
        content: "You received the requested item <a href='#{request_url(@request)}'>##{@request.id}</a>",
        event_type: Request.statuses[:completed])
  end

  def send_cancel_request_notification
    if @request.selected_offer
      # notify inbox
      CancelRequestNotification.create(
          receiver_id: @request.selected_offer.carrier_id,
          content: "The request #{@request.name} has been canceled")
    end
    CancelRequestNotification.create(
        receiver_id: @request.requester_id,
        content: "You canceled the requested item #{@request.name}")
  end

  def send_cancel_offer_notification
    CancelOfferNotification.create(
        receiver_id: @request.selected_offer.carrier_id,
        content: "You canceled your offer to help on <a href='#{request_url(@request)}'>##{@request.id}</a>")
    
    # notify inbox
    CancelOfferNotification.create(
        receiver_id: @request.requester_id,
        content: "#{@request.selected_offer.carrier.email} canceled his offer to help you on <a href='#{request_url(@request)}'>##{@request.id}</a>")
  end

  def send_reject_notification
    # notify inbox
    RejectNotification.create(
        receiver_id: @request.selected_offer.carrier_id,
        content: "#{@request.requester.email} has rejected your offer on <a href='#{request_url(@request)}'>##{@request.id}</a>")
  end

  def load_request
    @request = Request.find_by_id(params[:id])
  end

  def request_params
    params.require(:request).permit!
  end

  def check_user_edit
    if current_user != Request.find_by_id(params[:id]).requester
      flash[:error] = "You can't edit request of other people"
      redirect_to root_path
    end
  end

  def load_request_by_id
   @request = Request.find_by_id(params[:id])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def friendly_status(request)
    message = ''
    if request.open?
      message = "<h4><span class='label label-success'>Open</span></h4>"
    elsif request.pending_deposit?
      message = "<h4><span class='label label-default'>Pending Deposit</span></h4>"
    elsif request.deposited?
      message = "<h4><span class='label label-info'>Deposited</span></h4>"
    elsif request.waiting_delivery?
      message = "<h4><span class='label label-default'>Waiting Delivery</span></h4>"
    elsif request.completed?
      message = "<h4><span class='label label-success'>Completed</span></h4>"
    end
    message.html_safe
  end

  def status_name(status)
    status.gsub('_', ' ').capitalize
  end

  def reviewee_name(request)
    if request.can_give_requester_review?(current_user)
      request.selected_offer.carrier.email
    elsif request.can_give_helper_review?(current_user)
      request.requester.email
    else
      ''
    end
  end

  def rating_class_name(rating, star_number)
    if star_number <= rating
      'glyphicon-star'
    else
      'glyphicon-star-empty'
    end
  end
end

app/views/requests/_item_delivered_form.html.erb
<form method="post" action="<%= item_delivered_request_path(@request) %>" class="btn-form" data-remote="true">
  <%= token_tag %>
  <button type="submit" class="btn btn-success">Delivered!</button>
</form>

app/views/requests/_offer_form.html.erb
<% if current_user %>
    <% if @request.can_make_new_offer?(current_user) %>
        <hr/>
        <div class='flash-messages'>
          <%= flash_messages(@request) %>
        </div>
        <button class="btn btn-primary"
                data-toggle="modal" data-target="#offer-modal">
          Offer to Help
        </button>
        <div class="modal fade" id="offer-modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-sm" role="document">
            <form method="post" action="<%= request_offers_path(@request) %>" data-remote="true">
              <%= token_tag %>
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">Offer to Help</h4>
                </div>
                <div class="modal-body">
                  <div class="form-group">
                    <label for="price">Offer Price</label>
                    <div class="input-group">
                      <span class="input-group-addon">VND</span>
                      <input type="number" class="form-control" value="<%= @request.offer_price %>" id="price" name="price"/>
                    </div>
                  </div>
                  <div class="form-group">
                    <% if @request.delivery_location %>
                    <label for="arrival_date">Return Date to <%= @request.delivery_location.name %></label>
                    <%end%>
                    <div class="input-group">
                      <input type="date" class="form-control" min="<%= DateTime.now.strftime('%Y-%m-%d') %>"
                             placeholder="dd/mm/yyyy" id="arrival_date" name="arrival_date"/>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-success">Confirm</button>
                  <button type="reset" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
              </div>
            </form>
          </div>
        </div>
    <% end %>
<% else %>
    <a href="<%= new_user_session_path %>" class="btn btn-success">Sign in to Help</a>
<% end %>

app/views/requests/_offer_section.html.erb
<% if @request.open? %>
    <%= render 'offer_form' %>
<% else %>
    <%= render 'offer_status' %>
<% end %>

app/views/requests/_offer_status.html.erb
<%= render 'traveller_info' %>

<% if current_user %>
    <% if @request.can_make_deposit?(current_user) %>
        <%= render 'deposit_form' %>
    <% elsif @request.can_make_purchase?(current_user) %>
        <%= render 'item_bought_form' %>
    <% elsif @request.can_make_deliver?(current_user) %>
        <%= render 'item_delivered_form' %>
    <% elsif @request.can_give_review?(current_user) %>
        <%= render 'review_form' %>
    <% end %>
<% else %>
    <hr/>
    <a href="<%= new_user_session_path %>" class="btn btn-success">Sign in to see more</a>
<% end %>

app/views/requests/_request.html.erb
 <div class="col-xs-4">
<div class="turn_off_hover">
  <%= link_to request_path(request) do %>    
    <div class="panel panel-default">
      <div class="panel-thumbnail">
       <%= image_tag request.picture_url, class: "img-responsive" %>
      </div>
      <div class="panel-body">
        <p class="lead text-center"><%= request.name %></p>
        
        <h4 class="text-center">
          <span class="label <%= status_color_for(request.status_to_s) %>">
          <%= request.status_to_s %></span>
        </h4>
        <div class="panel-footer">
          <table>
            <tbody>
              <td style="padding-right:10px">
                <%= image_tag request.requester.avatar, class: "avatar img-circle"%>
              </td>
              <td style="padding-top:5px">
                <p>
                  Buy in <%= request.selling_location.name %>
                  <br>
                  Willing to pay <%= request.offer_price %> VND
                </p>
              </td>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

  
</div><!--/col-->

app/views/requests/_traveller_info.html.erb
<hr/>
<p>
  <span class="glyphicon glyphicon-plane"></span>
  Traveller offered to help
</p>
<br/>
<div class="user-info">
  <div class="media">
    <div class="media-left media-middle">
      <img class="media-object img-circle avatar" src="<%= @request.selected_offer.carrier.avatar %>" alt="Requester Avatar">
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @request.selected_offer.carrier.email %></h4>
      <div class="user-rating">
        <% (1..5).each do |number| %>
            <span class="glyphicon <%= rating_class_name(@request.selected_offer.carrier.current_score, number) %>" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/cancel_offer.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @request.requester_id %>' }));
	window.location.href = '<%= request_path(params[:id]) %>';
<% end %>

app/views/requests/cancel_offer_manage.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @request.requester_id %>' }));
	window.location.href = '<%= manage_request_path %>';
<% end %>

app/views/requests/cancel_request.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @receiver_id %>' }));
	window.location.href = '<%= requests_path %>';
<% end %>

app/views/requests/cancel_request_manage.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @receiver_id %>' }));
	window.location.href = '<%= manage_request_path %>';
<% end %>

app/views/requests/edit.html.erb
<h2 class="text-center">Update Request</h2>
<%= render 'new_request/form_error' %>
<%= form_for @request do |f| %>
          <div class="form-group">
            <%= f.label :name, "Item name" %>
            <%= f.text_field :name, class:"form-control",
          placeholder: "What do you want to buy?"%>
          </div>
          <div class="form-group">
            <%= f.label :description, "Item description"%>
            <%= f.text_area :description, class:"form-control", 
              placeholder:"Describe your item e.g. size, quantity, colour, packaging, how to buy" %>
          </div>
          <div class="form-group">
            <%= f.label :picture_url,"Picture(url)" %>
            <%= f.text_field :picture_url,placeholder: "Optional", class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :links, "Link to item" %>
            <%= f.text_field :links, placeholder: "Optional", class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :selling_location_id, "Country to buy from" %> <br>
            <%= f.collection_select :selling_location_id, Location.all, :id, :name,{},
              {class: "form-control"}%>
          </div>
          <div class="form-group">
            <%= f.label :delivery_method_id, "Delivery option" %> <br>
            <%= f.collection_select :delivery_method_id, DeliveryMethod.all, :id, :name,
              {},{class: "form-control"}%>
          </div>
          <div class="form-group">
            <%= f.label :offer_price %><br>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">VND</span>
              <%= f.text_field :offer_price, class:"form-control" %>
            </div>
          </div>
        <div class="text-center">
          <%= button_tag(type: "submit", class: "btn btn-lg btn-primary", name: "commit", value: "conceal") do %>
            Update
            <span class="glyphicon glyphicon-chevron-right" 
                  style = "color: white" aria-hidden="true"></span>
        </div>

      <% end %> 
          
<% end %>

app/views/requests/index.html.erb
<h1 class="text-center">Requests from <%= params[:location]%></h1>
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <%= render "shared/filter" %>
  </div>
  <div class="col-xs-12 col-sm-6">
      <%= form_tag requests_path, method: :get do %>
        <div class="input-group">
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </div>
          <% if params[:location] %>
            <%= hidden_field_tag :location, params[:location] %>
          <% end %>
          <% if params[:order] %>
            <%= hidden_field_tag :order, params[:order] %>
          <% end %>
          <%= text_field_tag :search,'', class:"form-control", 
            placeholder: "Looking for something?" %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class:"btn btn-default" %>
          </span>
        </div>
      <% end %>
  </div>
</div>
<% @requests.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.each do |request| %>
          <% if request %>
            <%= render request %>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/requests/item_delivered.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @request.selected_offer.carrier_id %>' }));
	window.location.href = '<%= request_path(params[:id]) %>';  
<% end %>

app/views/requests/reject.js.erb
$('.flash-messages').empty().append('<%= flash_messages(@request) %>');

<% if @request.errors.empty? %>
	window.ws.send(JSON.stringify({ event: 'notification_create', receiver_id: '<%= @request.selected_offer.carrier_id %>' }));
	window.location.href = '<%= request_path(params[:id]) %>';  
<% end %>