config/routes.rb
Rails.application.routes.draw do
  get 'travel_plans/new'

  devise_for :users
  resources :new_request
  resources :comments
  resources :requests do
    member do
      post 'deposit'
      post 'item_bought'
      post 'item_delivered'
      post 'cancel_request'
      post 'cancel_offer'
      post 'reject'
      post 'cancel_request_manage'
      post 'cancel_offer_manage'
      post 'rate'
    end
    resources :offers
  end
  resources :travel_plans
  get '/manage/request' => 'manager#requests'
  get '/manage/trip' => 'manager#trips'
  get '/inbox' => 'inbox#show'
  root 'home#index'
  get '/trip' => 'trips#new'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <a name="about-us"></a>
    <p class="contact-us"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;72 Lê Thánh Tôn, Phường Bến Thánh, Q1,
      HCMC, VietNam</p>
    <p class="contact-us"><i class="glyphicon glyphicon-earphone"></i>&nbsp;&nbsp;+84 90 674 8189</p>
    <p class="contact-us"><i class="glyphicon glyphicon-envelope"></i>&nbsp;&nbsp;support@simple.com</p>
    <br>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default bg-faded" id="navlink">
  <a href="/"><img class="navbar-brand" src="/easycarry6.png"></a>
  <ul class="nav navbar-nav pull-right">
    <li class="nav-item">
      <a class="nav-link" href="<%= travel_plans_path %>">Browse</a>
    </li>
    <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                                              role="button" aria-haspopup="true" 
                                              aria-expanded="false">
            Manage <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a class="nav-link" href="/new_request">New request</a></li>
            <li><a class="nav-link" href="<%= new_travel_plan_path %>">New Travel Plan</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Your requests and offers', '/manage/request', 
              class:"nav-link" %></li>
            <li><%= link_to 'Your trips', '/manage/trip', 
              class:"nav-link" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <a id='nav-inbox-link' class="nav-link" href="<%= inbox_path %>">Inbox </a>
        </li>
    <% end %>
    <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <div class="profile-image">
                <%= image_tag current_user.avatar, class: "img-circle avatar2" %>
              </div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu">
                <li><%= link_to "Sign out", destroy_user_session_path, 
                        method: :delete, class: 'nav-link'%></li>
            </ul>
        </li>
    <% end %>
    <% if not user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Login/Register</a>
        </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplecarry</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
    Stripe.setPublishableKey('pk_test_WXc5X6G8lUagOQNiglRU67cA');
  </script>
  <%= csrf_meta_tags %>
</head>
<body>

<span id="user-id" style="display: none;">
  <% if user_signed_in? %>
    <%= current_user.id %>
  <% end %>
</span>

<%= render 'layouts/header' %>
<div class="container">
  <%= flash_messages %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>